profiles:
  default:
    files:
      - target: "~/bashrc"
      - target: "~/vimrc"
  jimmy:
    files:
      - target: "~/.config/app/work_config.yaml"
      - target: "~/work_notes.txt"
  john:
    files:
      - target: "~/.config/app/personal_config.yaml"
      - target: "~/diary.txt"